NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GDERYRDAOITUY44PABGDBFUPYV4DDMYQZ5O3XX4FGBYIVOCN5NRXACXJ",
"GCG66QBAZJKYZY63QZW3JUYPPSYX6Z4HBPLZH2OLHMOXHQ4KENNBA7YA",
"GCJB7KEY5KFBZYEYJ524NODXSAMRN5Y6XM64BD7SF7ZWZICK7REB3DUF"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Stellarity"
ORG_URL="https://www.stellarity.org"
ORG_DESCRIPTION="In Stellar We Trust"
ORG_TWITTER="@Stellarity_"
ORG_LOGO="https://i.ibb.co/fkDv0cT/stellarity.png"
ORG_OFFICIAL_EMAIL="stellarityorg@gmail.com"


[[CURRENCIES]]
code="XLS"
issuer="GDERYRDAOITUY44PABGDBFUPYV4DDMYQZ5O3XX4FGBYIVOCN5NRXACXJ"
anchor_asset="false"
name="Stellarity"
desc="Stellarity is a decentralized, global new cryptocurrency with qualified crypto trading groups that allows you to transfer currency with a stellar-based wallet with almost non-existent fees. Learn more about Stellarity at https://stellarity.org/"
conditions="There will only ever be 10 million XLS tokens in existence"
image="https://i.ibb.co/fkDv0cT/stellarity.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#XLS was issued using the open and inclusive Stellar blockchain network.


[[CURRENCIES]]
code="XLR"
issuer="GCG66QBAZJKYZY63QZW3JUYPPSYX6Z4HBPLZH2OLHMOXHQ4KENNBA7YA"
anchor_asset="false"
name="Interstellar"
desc="Interstellar is a new generation token based on Stellar blockchain technology, one of the most recommended platforms for crypto coins around the world. Interstellar focuses attention on the block-chain technology and eliminates the chance of fraud, censorship or third-party involvement. The blockchain is a public ledger that records cryptic transactions, an innovative solution that accomplishes this without any external regulating authority. Learn more about Stellarity at https://stellarity.org/"
conditions="There will only ever be 10 million XLR tokens in existence"
image="https://i.ibb.co/pfS3Mkt/interstellar.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#XLR was issued using the open and inclusive Stellar blockchain network.


[[CURRENCIES]]
code="XLX"
issuer="GCJB7KEY5KFBZYEYJ524NODXSAMRN5Y6XM64BD7SF7ZWZICK7REB3DUF"
anchor_asset="false"
name="Stellarix"
desc="Stellarix is a new DeFi token strongly enough to support complex trading schemes on an entirely decentralized network. XLX executes a number of unique technology innovations, which enable responsive trading of derivatives in a decentralized environment. Stellarix aims to create a freelance commerce to promote impeccable, risk-free integration between freelancers and buyers at minimal cost on the basis of QFS."
conditions="There will only ever be 10 million XLX tokens in existence"
image="https://i.ibb.co/pZqRFzS/logo-x.png"
fixed_number=10000000
max_number=10000000
is_unlimited=false
#XLX was issued using the open and inclusive Stellar blockchain network.
